# LangChain Platform Configuration for MCP SSE Client
name: "mcp-sse-client"
version: "0.1.0"
description: "SSE-based MCP Client with LangChain integration"

# Runtime configuration
runtime:
  type: "python"
  version: "3.13"
  entrypoint: "langchain_client.py"

# Environment variables
environment:
  required:
    - OPENAI_API_KEY
  optional:
    - LANGCHAIN_API_KEY
    - LANGCHAIN_TRACING_V2
    - LANGCHAIN_PROJECT
    - MCP_SERVER_URL

# Default configuration
defaults:
  mcp_server_url: "https://web-production-b40eb.up.railway.app/sse"
  model_name: "gpt-4o-mini"
  temperature: 0.0